# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Douban', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_active',
            new_name='userActive',
        ),
    ]
