# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Douban', '0002_auto_20180318_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractive',
            name='status',
            field=models.CharField(default='r', max_length=1),
        ),
    ]
