# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Douban', '0003_useractive_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractive',
            name='username',
        ),
    ]
