# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 04:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Douban', '0004_remove_useractive_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractive',
            name='username',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
