# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='clickNum',
            new_name='click_num',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='goodNum',
            new_name='good_num',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Time',
            new_name='pub_time',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Writer',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='goodNum',
            new_name='good_num',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='woWhichId',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='fromId',
            new_name='commenter_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='Time',
            new_name='pub_time',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='eMail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='followNum',
            new_name='follow_num',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Time',
            new_name='pub_time',
        ),
        migrations.RemoveField(
            model_name='books',
            name='Writer',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nickName',
        ),
        migrations.AddField(
            model_name='books',
            name='writer',
            field=models.CharField(default='', max_length=50, verbose_name='作者名'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default='', verbose_name='评论内容'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='users',
            name='nick_name',
            field=models.CharField(default='小豆瓣儿', max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='goodlink',
            name='bookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Books', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='goodlink',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users', verbose_name='点赞的人'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.CharField(default='image/default.png', max_length=100, verbose_name='用户头像'),
        ),
    ]
