# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.CharField(default='../../../media/pictures/defalut_avatar.png', max_length=100, verbose_name='用户头像'),
        ),
    ]
