# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 07:35
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
