# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='src',
            field=models.ImageField(default='/media/pictures/defalut_avatar.png', upload_to='media/pictures/', verbose_name='封面url地址'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='/media/pictures/defalut_avatar.png', upload_to='media/pictures/', verbose_name='用户头像'),
        ),
    ]
