# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractive',
            name='username',
        ),
        migrations.AddField(
            model_name='useractive',
            name='email',
            field=models.EmailField(default=123, max_length=254, verbose_name='用户'),
            preserve_default=False,
        ),
    ]
