# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 00:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 8, 9, 31, 339327), verbose_name='发表时间'),
        ),
    ]
