# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 09:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectionArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Books', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏文章',
                'verbose_name_plural': '用户收藏文章',
            },
        ),
        migrations.CreateModel(
            name='UserCollectionBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Books', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏书籍',
                'verbose_name_plural': '用户收藏书籍',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='nick_name',
            field=models.CharField(default='小豆瓣', max_length=30, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='users',
            name='signature',
            field=models.CharField(default='这个人很懒，还什么都没说', max_length=30, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 17, 29, 37, 275093), verbose_name='发表时间'),
        ),
        migrations.AddField(
            model_name='usercollectionbooks',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='usercollectionarticles',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
