# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20180407_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='邮箱'),
        ),
    ]
