# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_users_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='signature',
            field=models.CharField(default='这个人很懒，还什么都没说', max_length=30, verbose_name='个性签名'),
        ),
    ]
