# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20180403_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间'),
        ),
    ]
