# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20180407_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='src',
            field=models.CharField(default='/media/book_image/defalut.png', max_length=100, verbose_name='封面url地址'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.CharField(default='/media/pictures/defalut_avatar.png', max_length=100, verbose_name='用户头像'),
        ),
    ]
