# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20180407_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='type',
            field=models.CharField(default='其他', max_length=10, verbose_name='图书分类'),
        ),
    ]
