# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20180405_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='signature',
        ),
        migrations.AddField(
            model_name='books',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间'),
        ),
    ]
