# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20180317_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='click_num',
        ),
    ]
