# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20180407_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_introduction',
            field=models.CharField(default='暂无介绍', max_length=50, verbose_name='作者简介'),
        ),
        migrations.AddField(
            model_name='books',
            name='author_picture',
            field=models.CharField(default='/media/book_image/defalut_author.png', max_length=100, verbose_name='作者照片'),
        ),
    ]
