# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectionarticles',
            name='Articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Articles', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='usercollectionbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Books', verbose_name='书籍'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='D:\\Python\\Test2\\Douban\\Douban\\image/\\pictures\\defalut_avatar.jpg', upload_to='', verbose_name='用户头像'),
        ),
    ]
