# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_articles_click_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
