# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20180405_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='user', max_length=20, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
