# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_useractive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='writer',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='writer',
            new_name='author',
        ),
    ]
