# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20180406_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectionarticles',
            name='Articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Articles', verbose_name='用户'),
        ),
    ]
