# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20180409_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='src',
            field=models.ImageField(default='/media/book_image/defalut.png', upload_to='media/pictures/', verbose_name='封面url地址'),
        ),
    ]
