# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20180329_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='followlink',
            name='toId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='被关注者', to=settings.AUTH_USER_MODEL, verbose_name='被关注者'),
        ),
        migrations.AlterField(
            model_name='followlink',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='关注者', to=settings.AUTH_USER_MODEL, verbose_name='关注者'),
        ),
        migrations.AlterField(
            model_name='goodlink',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞者'),
        ),
    ]
