# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20180405_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='user', max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
