# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 10:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20180329_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractive',
            options={'verbose_name': '用户激活验证码', 'verbose_name_plural': '用户激活验证码'},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='good_num',
            new_name='like_num',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='good_num',
            new_name='like_num',
        ),
        migrations.AlterField(
            model_name='articles',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 18, 16, 53, 338059), verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='useractive',
            name='activation_code',
            field=models.CharField(max_length=30, verbose_name='激活码'),
        ),
        migrations.AlterField(
            model_name='useractive',
            name='status',
            field=models.CharField(default='r', max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='useractive',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('F', '女'), ('M', '男'), ('S', '保密')], default='保密', max_length=1, verbose_name='性别'),
        ),
    ]
