# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20180329_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='src',
            field=models.CharField(default='image/default.png', max_length=100, verbose_name='封面url地址'),
        ),
        migrations.AddField(
            model_name='books',
            name='text',
            field=models.TextField(default='暂无介绍', verbose_name='简介'),
        ),
    ]
