# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20180331_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 18, 17, 25, 825421), verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='follow_num',
            field=models.IntegerField(default=0, verbose_name='被关注数'),
        ),
    ]
