# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20180331_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 18, 31, 57, 370056), verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('F', '女'), ('M', '男'), ('S', '保密')], default='S', max_length=1, verbose_name='性别'),
        ),
    ]
